### ISSUE TITLE
Unable to enter widget

### ISSUE THREAD

**Issue by exa18** [F4uzan/HgLauncher#104]
**What's the issue?**
On widget screen is imposible to enter to any element. 
Holding down over widget brings editing menu but slighly too long wait for it.

**To reproduce…**
1. enter apps list
2. slide to widget screen
3. try click on any widget

**Expected behavior**
After click on I expect to enter widget settings or detailed view.

**What did you see instead?**
Nothing.

**Screenshots**
no need.

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi 9
 - Android version: 10 (MIUI 11 and 12)
 - HgLauncher version: 1.5.1

**Comment by F4uzan** [comment]
May I know the widgets used? I can't reproduce this issue on my end, and my widgets work as intended.

**Comment by exa18** [comment]
KLARA: https://play.google.com/store/apps/details?id=org.androworks.klara
EVENT FLOW CAL: https://play.google.com/store/apps/details?id=com.syncedsynapse.eventflowwidget

**Comment by grokkingnix** [comment]
I have some additional information on this issue. Something similar is happening to me with the widget space.

When trying to add a new widget (new launcher install) pressing the "+" button apparently does nothing. When pressing it again an error shows on screen "Settings keeps stopping".

Interestingly this is happening on a Xiaomi device as well, here are the details of the phoine:
MIUI Version: ```MIUI Global 14.0.8```
Android Version: ```13TP1A.220624.014```
Kernel Version: ```4.19.191-g10f0e8e5985e```

There is also a log of the exception as well:

```
android.view.InflateException: Binary XML file line #17 in com.android.settings:layout/pick_item: Binary XML file line #17 in com.android.settings:layout/pick_item: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #17 in com.android.settings:layout/pick_item: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at android.view.LayoutInflater.createView(LayoutInflater.java:883)
at android.view.LayoutInflater.createView(LayoutInflater.java:805)
at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:959)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:979)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1035)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
at android.view.LayoutInflater.inflate(LayoutInflater.java:688)
at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
at com.android.settings.ActivityPicker$PickAdapter.getView(ActivityPicker.java:316)
at android.widget.AbsListView.obtainView(AbsListView.java:2420)
at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
at android.widget.ListView.onMeasure(ListView.java:1323)
at android.view.View.measure(View.java:26854)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26854)
at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:146)
at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:71)
at android.view.View.measure(View.java:26854)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26854)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26854)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
at android.view.View.measure(View.java:26854)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4277)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3225)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2647)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9790)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1402)
at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
at android.view.Choreographer.doFrame(Choreographer.java:911)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8321)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0403c5 a=26}, theme={InheritanceMap=[id=0x10303eeandroid:style/Theme.DeviceDefault.Dialog.Alert.DayNight, id=0x10302d1android:style/Theme.DeviceDefault.Dialog.Alert, id=0x1030226android:style/Theme.Material.Dialog.Alert, id=0x1030434android:style/Theme.Material.Dialog.BaseAlert, id=0x1030225android:style/Theme.Material.Dialog, id=0x1030432android:style/Theme.Material.BaseDialog, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[android:style/Theme.DeviceDefault.Dialog.Alert.DayNight, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1010)
at android.content.res.TypedArray.getDrawable(TypedArray.java:994)
at android.view.View.<init>(View.java:5651)
at android.widget.TextView.<init>(TextView.java:1082)
at android.widget.TextView.<init>(TextView.java:1076)
at android.widget.TextView.<init>(TextView.java:1072)
... 50 more
```
