### ISSUE TITLE
Crashes on widget screen

### ISSUE THREAD

**Issue by exa18** [F4uzan/HgLauncher#96]
**What's the issue?**
App crashes more frequently than previous version 1.4.x
on widget screen and sometimes on app list when I try use search bar.

**To reproduce…**
1. enter apps list
2. slide to widget screen

**Expected behavior**

**What did you see instead?**
App unexpectly stoped window.
Sometimes it crashes all the time and other only once.

**Screenshots**

**Device information (please complete the following information):**
 - Device: X005 Asus
 - Android version: 5.1
 - HgLauncher version: 1.5.0
On widget screen I have: Klara, Event Flow Widget.
On side gestures: left -> chrome, right -> lite, down -> K-9 mail, up -> contacts

**Comment by F4uzan** [comment]
I have been looking at this issue lately. I have been unable to reproduce it, which may take me some time to figure out the root cause of the issue.

However, seeing that I also have received similar reports from Play Store, I can confirm that this is a widespread issue. I'll see what I can do to track this one out before I roll 1.5.0.1.

**Comment by rhjdvsgsgks** [comment]
hi, i found something maybe helpful to resolve this bug.
i enable some accessibility service which have "Observe your actions" and "Retrieve window content" permission. after open this launcher, all of those accessibility application will keep crashing, and here is the log.
```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createException(Parcel.java:1978)
	at android.os.Parcel.readException(Parcel.java:1935)
	at android.os.Parcel.readException(Parcel.java:1885)
	at android.accessibilityservice.IAccessibilityServiceConnection$Stub$Proxy.findAccessibilityNodeInfoByAccessibilityId(IAccessibilityServiceConnection.java:451)
	at android.view.accessibility.AccessibilityInteractionClient.findAccessibilityNodeInfoByAccessibilityId(AccessibilityInteractionClient.java:343)
	at android.view.accessibility.AccessibilityRecord.getSource(AccessibilityRecord.java:186)
```

**Comment by F4uzan** [comment]
Thank you for the log @rhjdvsgsgks and the reproduction steps. At the moment I'm holding Hg's development in a pause due to the lack of time, but I'll try poking through when I can. The log seems to be concise enough for it.

**Comment by jiangnan44** [comment]
@F4uzan  hi man,have you figure out the cause of this bug?  and any idea or solution? I'm developing an app based on accessibilityservice,too, and got this  same problem. I can't do nothing but violently try-catch it.
